### ISSUE TITLE
Add joint initiation to doc

### ISSUE THREAD

**Issue by degenaro** [oscal-compass/compliance-trestle-fedramp#47]
## Issue description / feature objectives

Jointly initiated by [IBM](www.ibm.com) and [Red Hat](https://www.redhat.com)

## Caveats / Assumptions

None

## Completion Criteria

Doc updated.

**Comment by jpower432** [comment]
@degenaro Can this be closed?

**Comment by degenaro** [comment]
Closing as N/A.
